version: "3.12"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: 
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            daphne -b 0.0.0.0 -p 8000 app.route:application"
    environment:
      - DB_HOST=db
      - DB_NAME=youtube
      - DB_USER=mingming96
      - DB_PASS=alswjd123
    depends_on:
      - db

  # app: 과 같은 뎁스로
  db:
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=youtube
      - POSTGRES_USER=mingming96
      - POSTGRES_PASSWORD=alswjd123